[package]
name = "rm-improved"
version = "0.5.0"
authors = ["mail@nivekuil.com"]
description = "A safety-focused alternative to rm."
repository = "https://github.com/nivekuil/rip"
license = "GPL-3.0+"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
clap = "2"
walkdir = "0.1"

[profile.release]
lto = true
