[package]
name = "rm-improved"
version = "0.6.1"
authors = ["mail@nivekuil.com"]
description = "rip: a safety-focused alternative to rm."
repository = "https://github.com/nivekuil/rip"
license = "GPL-3.0+"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
clap = "2"
walkdir = "0.1"
libc = "0.2"

[profile.release]
lto = true

[[bin]]
name = "rip"
